Lh/hex results
Element84/filmdrop-ui pull request #109
Opened 2023-04-20 19:07 UTC by lucyhutcheson

**Related Issue(s):**

- N/A

**Proposed Changes:**

1.  Add geo hex grid display for low zoom levels when available per collection

**PR Checklist:**

- [X] I have added my changes to the [CHANGELOG](https://github.com/Element84/filmdrop-ui/blob/main/CHANGELOG.md) **or** a CHANGELOG entry is not required.

2023-04-21 13:22 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +  const h3 = require('h3-js')
should be `import * as h3 from 'h3-js'` at the top of the file instead of require

2023-04-21 13:25 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +    const hexBoundary = h3.cellToBoundary(feature.key)
```suggestion
    const hexBoundary = h3.cellToBoundary(feature.key, true)
```

this returns the boundaries in geojson lon/lat order and "closes the loop" by having the start and end vertex be the same (https://github.com/uber/h3-js#h3celltoboundaryh3index-formatasgeojson--arraycoordpair)

2023-04-21 13:28 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +    const hexBoundary = h3.cellToBoundary(feature.key)
with the cellToBoundary change, there's still an issue because the antimeridan-crossing polygons splat the map (that's a new term I just made up). I think what needs to be done is the coordinates need to be changed so that if the polygon crosses the antimeridan, all of the longitude coordinates need to either be positive (past 180) or negative (past -180) to show on the map

2023-04-21 15:26 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +    const hexBoundary = h3.cellToBoundary(feature.key)
This has been resolved.

2023-04-24 18:15 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +    const hexBoundary = h3.cellToBoundary(feature.key)
This has been resolved.

2023-04-26 14:07 UTC, philvarner commented
I searched with S2 selected (the Zoom in msg displayed), then I switched to Cop dem and searched, and the message stayed
This doesn't happen if I switch to COP DEM and then search
however, I could see it being useful to have some message about needing to zoom in always displaying when at the hex level

2023-04-26 14:11 UTC, philvarner commented
The legend is off wrt to the color values displayed:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/124996/234601750-39cfaf47-4098-4d4f-a119-be4aa1fc2d3a.png">

2023-04-26 14:13 UTC, philvarner commented
related to that, the combination of the dark basemap and the opacity of the cell mean that it appears a lot less saturated than the colormap value (and consequently the legend value). I'm not sure what the right solution for that is.

2023-04-26 14:16 UTC, philvarner commented
Maybe consider only showing the scene count on mouseover? This is pretty busy:

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/124996/234604185-6636280f-becc-4ec4-8a63-483c68a7c893.png">

2023-04-26 14:19 UTC, philvarner commented
At this zoom level, there are several cells that appear to be there (the labels show up) but the shape and color are missing:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/124996/234604740-8632ab3a-5657-426c-a7bc-59828a5145ef.png">

I zoomed in a level and they're covered by the next precision level, so odd...

2023-04-26 16:25 UTC, philvarner commented
<img width="366" alt="image" src="https://user-images.githubusercontent.com/124996/234607179-a169e3e3-93bb-452b-aacb-37442321a610.png">

I think we could improve this message by adding the overflow count, e.g., "2000 grid cells, 3424 scenes total, 101 scenes not represented"

2023-04-26 16:27 UTC, philvarner commented
Should changing the collection clear the footprints and imagery on the screen? I think it should.

2023-04-26 17:00 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +  const apiKeys = apiResponse.aggregations?.find(
apiKeys is an odd name for this variable. maybe just buckets?

2023-04-26 17:06 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +    let posPoints = 0
a little confusing that they're named 'pos' and 'neg', but it's really >100 and <-100

2023-04-26 17:06 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +    const positive = posPoints > negPoints
positive => "has_more_positive"

2023-04-26 17:08 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +    largestRatio = colorRatio > largestRatio ? colorRatio : largestRatio
```suggestion
    const largestRatio = colorRatio > largestRatio ? colorRatio : largestRatio
```

2023-04-26 17:08 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +  let largestFrequency = 0
remove and use the consts below

2023-04-26 17:11 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +  })
this is a long map function -- maybe consider breaking out into additional functions

2023-04-26 17:13 UTC, philvarner requested changes
inline comments

2023-04-26 19:02 UTC, lucyhutcheson commented on src/utils/colorMap.js
> +    colormap: 'viridis',
This is done.

2023-04-26 19:13 UTC, lucyhutcheson commented on src/components/Search/Search.js
> +  function getResults({ typeOfSearch, gridCode }) {
I was testing a more complex object functionality but switched to something else. It's been reverted.

2023-04-26 19:14 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +  const apiKeys = apiResponse.aggregations?.find(
I agree. I updated the hex function and now updated this one.

2023-04-26 19:21 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +    (el) => el.name === frequency
This has been updated.

2023-04-26 19:27 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +    const longArray = hexBoundary.map((element) => element[0])
Done.

2023-04-26 19:32 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +    largestRatio = colorRatio > largestRatio ? colorRatio : largestRatio
This variable is declared outside of the map function due to scope issues. It is returned in the final return function at the end of the parent function. See line 160.

2023-04-26 19:32 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +  let largestFrequency = 0
These variables are declared here due to scope issues. It is returned in the final return function at the end of the function. See line 160.

2023-04-26 19:33 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +    largestFrequency =
This variable is declared outside of the map function due to scope issues. It is returned in the final return function at the end of the parent function. See line 160.

2023-04-26 19:35 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +  })
With the anti merdian stuff broken out, it's a much smaller map function.

2023-04-27 12:41 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +      // for multipolygon grid cells, extract the next array
I think this will cause MultiPolygons to only have the first Polygon in their array of Polygons displayed?

2023-04-27 12:41 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +  // get general location of polygon points above/below zero
```suggestion
  // get general location of polygon points east or west of antimeridian
```

2023-04-27 12:58 UTC, philvarner commented on src/components/Layout/Content/BottomContent/BottomContent.js
> +  const resultType = _searchType === 'hex' ? 'hex cells' : 'grid cells'
there are a few cases of these values like _searchType that are enums, but currently just raw strings. Instead, they should use an enum pattern like this https://www.sohamkamani.com/javascript/enums/#enums-with-classes

2023-04-27 13:10 UTC, philvarner commented
In grid:code view, clicking a grid cell doesn't bring up the metadata panel any longer.

2023-04-27 13:14 UTC, philvarner commented
In mosaic mode, the counts are wrong:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/124996/234872278-06ad0fc9-379b-4909-be08-20863f3363b1.png">

<img width="306" alt="image" src="https://user-images.githubusercontent.com/124996/234872583-7c4c4534-399e-422f-a07f-e465d3034104.png">

10 is the default number of items from a search if you don't specify a limit, and 1221592 is how many total items we have in dev.

2023-04-27 15:16 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +  // get general location of polygon points above/below zero
This has been updated.

2023-04-27 15:18 UTC, lucyhutcheson commented on src/utils/colorMap.js
> +    nshades: Math.round(largestRatio) > 9 ? Math.round(largestRatio) : 9,
This has been updated.

2023-04-27 16:37 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +      // for multipolygon grid cells, extract the next array
This has been fixed.

2023-04-27 19:38 UTC, philvarner approved these changes

2023-04-27 20:52 UTC, merged