Updates for version 0.3.0
Element84/filmdrop-ui pull request #3
Opened 2023-01-24 19:13 UTC by lucyhutcheson

This update adds a dynamically populated Collections dropdown and error handling.

2023-01-24 21:26 UTC, philvarner commented on src/components/PopupResult/PopupResult.js
> +                <source
I think we can remove the source element , since it's always going to be the same asset offered by the img element.

2023-01-24 21:29 UTC, philvarner commented on src/components/PopupResult/PopupResult.js
> +  let thumbnail = props.result?.links?.filter(({ rel }) => rel === 'thumbnail')[0].href;
```suggestion
  let thumbnail = props.result?.links?.find(({ rel }) => rel === 'thumbnail')?.href;
```

2023-01-24 21:30 UTC, philvarner commented on src/components/PopupResult/PopupResult.js
> +  if (collection === "sentinel-2-l1c") { thumbnail = ""};
this `if` statement can be removed after making the other change to finding the thumbnail.

2023-01-24 21:33 UTC, philvarner commented on src/components/PopupResult/PopupResult.js
> +  let thumbnail = props.result?.links?.filter(({ rel }) => rel === 'thumbnail')[0].href;
I'm curious as to why this doesn't throw an index out of bounds exception when the thumbnail asset doesn't exist, since that should return an array of size 0 and then try to get the 0th element.

2023-01-24 21:36 UTC, philvarner commented on src/components/Search/Search.js
> +  const twoWeeksAgo = new Date(Date.now() - 1209600000);
refactor the time offset into a top-level constant that uses the formula to compute it to make it clear that it's the right offset

2023-01-24 21:56 UTC, philvarner commented on src/components/Search/Search.js
> +    const rgbAssetNames = "red&assets=green&assets=blue";
I think this would be clearer and less-error prone to future changes if the entire assets and color_formula were set fully and separately here. 

So, single asset name should be:

let assetParameter = "&assets=visual"
const rgbAssetNames = "&assets=red&assets=green&assets=blue"
let colorAdjustment = ""

and then colorAdjustment would also be added to the URL below.

2023-01-24 22:00 UTC, philvarner commented on src/components/Search/Search.js
> +    const rgbAssetNames = "red&assets=green&assets=blue";
I filed this issue to pull this out of the code and into config https://github.com/Element84/filmdrop-ui/issues/4

2023-01-25 23:01 UTC, lucyhutcheson commented on src/components/PopupResult/PopupResult.js
> +                <source
This has been removed.

2023-01-25 23:02 UTC, lucyhutcheson commented on src/components/PopupResult/PopupResult.js
> +  let thumbnail = props.result?.links?.filter(({ rel }) => rel === 'thumbnail')[0].href;
This has been updated.

2023-01-25 23:24 UTC, lucyhutcheson commented on src/components/PopupResult/PopupResult.js
> +  if (collection === "sentinel-2-l1c") { thumbnail = ""};
If I remove this, the image will display broken because there is a thumbnail URL for Sentinel 2 L1C but it doesn't resolve even if the URL exists. 

https://earth-search.aws.element84.com/v1/collections/sentinel-2-l1c/items/S2A_17SKC_20230124_0_L1C/thumbnail

2023-01-25 23:47 UTC, lucyhutcheson commented on src/components/Search/Search.js
> +  const twoWeeksAgo = new Date(Date.now() - 1209600000);
This has been resolved.

2023-01-26 14:12 UTC, philvarner commented on src/components/PopupResult/PopupResult.js
> +  let thumbnail = props.result?.links?.filter(({ rel }) => rel === 'thumbnail')[0].href;
as in the other comment, I forgot that the link always exists -- it's the asset that may not.

2023-01-27 21:12 UTC, lucyhutcheson commented on src/components/PopupResult/PopupResult.js
> +  if (collection === "sentinel-2-l1c") { thumbnail = ""};
This has been resolved.

2023-01-27 23:20 UTC, lucyhutcheson commented on src/components/Search/Search.js
> +    const rgbAssetNames = "red&assets=green&assets=blue";
This has been resolved.

2023-01-30 19:10 UTC, philvarner commented on .env.development
> +REACT_APP_ASSET_CONFIGURATIONS=[{"collection":"sentinel-2-l2a","asset":"&assets=visual"}]
Few comments:
- I'd prefer if this were named REACT_APP_TILER_CONFIGURATION
- `asset` renamed `assets`
- add the landsat example
- the `assets` value should just be the name of the asset if there's only one, so just `visual`. If there are several, then it should be the rest of the values after the first one, e.g., `red&assets=green&assets=blue`. Then the tiler url is constructed like "`&assets=${assets_value}`
- add `color_formula` as a separate configuration, which may not exist, so the url generation needs to only add `&color_formula=` if it is defined.

2023-01-30 19:15 UTC, philvarner commented on src/components/CollectionDropdown/CollectionDropdown.js
> +    fetch(API_ENDPOINT+`/collections`)
```suggestion
    fetch(`${API_ENDPOINT}/collections`)
```

2023-01-30 19:17 UTC, philvarner commented on src/components/Search/Search.js
> +      setdrawboxBtnError(true);
Just curious why the first D is lowercase, instead of following the lowerCamelCase convention?

2023-01-30 19:22 UTC, philvarner commented on src/components/Search/Search.js
> +    // Set up assets from environment variable
this processing shouldn't be done every time the addImageClicked method is done, it should be done once when the app is initialized.

Also, the configuration JSON should be processed into a Map where the assets and color_formula can be looked up by collection name, rather than having to use find to search the list.

Additionally, this should handle the case where the collection doesn't have any configuration. Right now, `(envAssets?.find(element => element.collection === _collectionSelected))` will be `undefined` and then thrown an exception with the attempt to access `.asset`

2023-01-30 19:23 UTC, philvarner commented on src/components/Search/Search.js
> +            assetParameters +
as mentioned before, split this into `assets` and `color_formula` parameters, and conditionally add them to the URL string if they're defined.

2023-01-30 19:24 UTC, philvarner requested changes
configuration and processing changes requested.

2023-01-31 20:22 UTC, lucyhutcheson commented on .env.development
> +REACT_APP_ASSET_CONFIGURATIONS=[{"collection":"sentinel-2-l2a","asset":"&assets=visual"}]
This has been resolved.

2023-01-31 20:24 UTC, lucyhutcheson commented on src/components/CollectionDropdown/CollectionDropdown.js
> +    fetch(API_ENDPOINT+`/collections`)
This has been updated.

2023-01-31 20:50 UTC, lucyhutcheson commented on src/components/Search/Search.js
> +            assetParameters +
This has been updated

2023-01-31 23:12 UTC, lucyhutcheson commented on src/components/Search/Search.js
> +      setdrawboxBtnError(true);
Was following the precedent set by original code, but have updated this to be more consistent with coding standards.

2023-02-02 19:44 UTC, lucyhutcheson commented on src/components/Search/Search.js
> +    // Set up assets from environment variable
This has been resolved.

2023-02-02 20:33 UTC, philvarner commented on .env.development
> +REACT_APP_ASSET_CONFIGURATIONS=[{"collection":"landsat-c2-l2","assets":"red&assets=green&assets=blue"}]
can you add back the sentinel-2-l2a asset configuration to show what it should look like for a single asset?

2023-02-02 20:35 UTC, philvarner commented on package.json
> +    "lint": "eslint \"**/*.js\" && echo \"👍  Passed linting\n\""
```suggestion
    "lint": "eslint \"**/*.js\" && echo \"👍  Passed linting\n\"",
    "lint-fix": "eslint --fix \"**/*.js\"",
```

2023-02-02 20:41 UTC, philvarner commented on .env.development
> +REACT_APP_ASSET_CONFIGURATIONS=[{"collection":"landsat-c2-l2","assets":"red&assets=green&assets=blue"}]
the variables REACT_APP_ASSET_CONFIGURATIONS and REACT_APP_COLOR_FORMULA should have a consistent naming scheme. I'd name them REACT_APP_TITILER_ASSETS and REACT_APP_TITILER_COLOR_FORMULAS

2023-02-02 20:42 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +  let envColorFormula = ''
envColorFormula => envColorFormulas

2023-02-02 20:44 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +  return (`&assets=${assetsValue}&color_formula=${colorFormula}&return_mask=true`)
remove unnecessary parens

2023-02-02 20:52 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +// function to parse through environment variables
how is this file used? I don't seen any references to it or the processEnvVars function

2023-02-02 20:54 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +  return (tilerConfigurationURL)
```suggestion
  return process.env.REACT_APP_TILER_CONFIGURATION || ''
```

2023-02-02 21:02 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +let envVariables = {}
This should be a const instead of let, a Map instead of object, and computed on initialization instead of by calling processEnvVars.

I'd structure it like:

```
const envVariables = processEnvVarns()

const processEnvVars = () => {
  // construct a Map where the key is the collection name and the value is another Map that has two keys `assets` and `color_formula` with string values
  const map =  ....
  return map
}

```

2023-02-02 21:03 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +    envVariables = [...[envAssets, envColorFormula].reduce((m, a) => (
this is hard to understand. There should be a unit test that validates this works correctly.

2023-02-02 21:05 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +    const collectionValues = envVariables.filter(element => element.collection === defaultCollection)[0]
part of the reason that envVariables should be a map is that then this could be accessed like

```
envVariables[defaultCollection]
```

Also, if you do need to find the only one element in a list, you can use `find` instead of `filter` and `[0]`

2023-02-02 21:06 UTC, philvarner requested changes
configuration processing needs rework

2023-02-03 23:24 UTC, lucyhutcheson commented on .env.development
> +REACT_APP_ASSET_CONFIGURATIONS=[{"collection":"landsat-c2-l2","assets":"red&assets=green&assets=blue"}]
This has been resolved.

2023-02-03 23:24 UTC, lucyhutcheson commented on .env.development
> +REACT_APP_ASSET_CONFIGURATIONS=[{"collection":"landsat-c2-l2","assets":"red&assets=green&assets=blue"}]
This has been resolved.

2023-02-03 23:25 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +  return (`&assets=${assetsValue}&color_formula=${colorFormula}&return_mask=true`)
This has been updated

2023-02-03 23:25 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +  return (tilerConfigurationURL)
This has been resolved

2023-02-03 23:26 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +let envVariables = {}
This has been resolved

2023-02-03 23:26 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +    envVariables = [...[envAssets, envColorFormula].reduce((m, a) => (
This has been resolved

2023-02-03 23:26 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +    const collectionValues = envVariables.filter(element => element.collection === defaultCollection)[0]
This has been resolved

2023-02-06 13:54 UTC, philvarner commented on src/components/Layout/PageHeader/PageHeader.js
> +          <img src="/logo.png" alt="logo" className="headerLogoImage"></img>
Also add a configuration parameter for the alt text and change this with a description of what the logo looks like and says rather than just "logo".

2023-02-06 18:23 UTC, lucyhutcheson commented on src/components/Layout/PageHeader/PageHeader.js
> +          <img src="/logo.png" alt="logo" className="headerLogoImage"></img>
This has been resolved.

2023-02-06 22:53 UTC, philvarner commented on .env.development
> +PUBLIC_URL=http://example.com/
my understanding is that this is a env var provided by React at runtime, and that it doesn't need to set explicitly (and shouldn't be). Can you look into that?

2023-02-06 22:55 UTC, philvarner commented on src/components/Layout/PageHeader/PageHeader.js
> +  const ALT_TEXT = process.env.REACT_APP_LOGO_ALT_VALUE
no need to add VALUE at the end of this, I think just `LOGO_ALT` is a clear name.

2023-02-06 23:23 UTC, lucyhutcheson commented on .env.development
> +PUBLIC_URL=http://example.com/
"You may use this variable to force assets to be referenced verbatim to the url you provide (hostname included). This may be particularly useful when using a CDN to host your application."

https://create-react-app.dev/docs/advanced-configuration/

2023-02-07 15:24 UTC, philvarner commented on README.md
> +REACT_APP_TILER_COLOR_FORMULAS=[{"collection":"landsat-c2-l2","color_formula":"Gamma+RGB+1.7+Saturation+1.7+Sigmoidal+RGB+15+0.35"}]
duplicated color formulas

2023-02-07 22:50 UTC, philvarner commented on src/components/Layout/PageHeader/PageHeader.js
> +  const LOGO = process.env.REACT_APP_LOGO
```suggestion
  const LOGO = process.env.REACT_APP_LOGO_URL
```

2023-02-09 01:14 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +  return `&assets=${assetsValue}&color_formula=${colorFormula}&return_mask=true`
return_mask doesn't need to be added here because the default value in titiler is `true` and it's not configurable in filmdrop-ui

2023-02-09 01:16 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +export const constructTilerURL = () => {
this doesn't need to be a function -- constructTilerURL can just be assigned to the expression that's currently returned.

2023-02-09 01:19 UTC, philvarner commented on .env.development
> +REACT_APP_TILER_ASSETS=[{"collection":"sentinel-2-l2a","assets":"visual"},{"collection":"landsat-c2-l2","assets":"red&assets=green&assets=blue"}]
since we're passing in a JSON object for configuration here, I think it would be better to change the `assets` value from being a string to being an array of strings, so 

```
[
{"collection":"sentinel-2-l2a","assets":["visual"]},
{"collection":"landsat-c2-l2","assets":["red","green","blue"}]
```

and then the array would be join'ed with `&assets=` to generate the string to append to the titiler url.

2023-02-09 01:24 UTC, philvarner commented on src/components/Search/Search.js
> +  // eslint-disable-next-line
it seems suspicious that there's a disable here but then the line got modified by eslint?

2023-02-09 01:25 UTC, philvarner commented on src/components/Search/Search.js
>    function clickHandler (e) {
if the function doesn't have to be named clickHandler, it would be better to rename the function to have a more clear name than add  a comment that says what it does

2023-02-09 01:34 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +export const constructAssetsURL = (defaultCollection) => {
the parameter should be named something like `collection` rather than defaultCollection, since the purpose is to use something other thank the default collection

2023-02-09 01:35 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +  if (!defaultCollection) defaultCollection = process.env.REACT_APP_DEFAULT_COLLECTION
This statement seems like a symptom of a problem from the picker -- a collection id should always be passed to this function, and if it's not, then the method should error rather than using the default collection.

2023-02-09 01:43 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +  }
This should be rewritten to guard against an error occurring rather than catching and logging the error. The only error that can happen here is that the collection doesn't have a config, so that access returns undefined an then the .assets is attempted to be accessed. 

envVariables should always at least be an empty object (or better, a Map).

Instead, using the optional operator reduces these 13 lines to 2: 

```
const assetsValue = envVariables[defaultCollection]?.assets || ''
const colorFormula = envVariables[defaultCollection]?.color_formula || ''
```

2023-02-09 01:47 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +    {}
ideally, this would return a Map rather than an object.

2023-02-09 01:48 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +const processEnvVars = () => {
unit tests need to be added for this.

2023-02-09 02:05 UTC, philvarner commented on .env.development
> +REACT_APP_TILER_ASSETS=[{"collection":"sentinel-2-l2a","assets":"visual"},{"collection":"landsat-c2-l2","assets":"red&assets=green&assets=blue"}]
the other thing I just thought of is that we could just structure this the exact same as we want it for the in-memory map and make it a single parameter REACT_APP_TILER_PARAMS, e.g.,:
{"sentinel-2-l2a": { "assets":"visual"},"landsat-c2-l2": {"assets":["red","green","blue"], "color_formula":"Gamma+RGB+1.7+Saturation+1.7+Sigmoidal+RGB+15+0.35"}}

2023-02-09 02:06 UTC, philvarner commented on .env.development
> +REACT_APP_TILER_ASSETS=[{"collection":"sentinel-2-l2a","assets":"visual"},{"collection":"landsat-c2-l2","assets":"red&assets=green&assets=blue"}]
that would allow us to get rid of all the complex processing code that merges the lists.

2023-02-10 16:30 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +  return `&assets=${assetsValue}&color_formula=${colorFormula}&return_mask=true`
This has been resolved.

2023-02-10 16:50 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +export const constructTilerURL = () => {
This has been resolved.

2023-02-10 17:25 UTC, lucyhutcheson commented on .env.development
> +REACT_APP_TILER_ASSETS=[{"collection":"sentinel-2-l2a","assets":"visual"},{"collection":"landsat-c2-l2","assets":"red&assets=green&assets=blue"}]
This has been resolved.

2023-02-10 17:27 UTC, lucyhutcheson commented on src/components/Search/Search.js
> +  // eslint-disable-next-line
This has been resolved.

2023-02-10 18:01 UTC, lucyhutcheson commented on src/components/Search/Search.js
>    function clickHandler (e) {
This is resolved.

2023-02-10 18:02 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +export const constructAssetsURL = (defaultCollection) => {
This has been resolved.

2023-02-10 18:05 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +  if (!defaultCollection) defaultCollection = process.env.REACT_APP_DEFAULT_COLLECTION
This has been removed.

2023-02-10 18:12 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +  }
This has been resolved.

2023-02-10 18:16 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +    {}
This function has been removed as per comment above to combine assets and color formulas into one variable.

2023-02-10 18:17 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +const processEnvVars = () => {
This function has been removed as per comment above to combine assets and color formulas into one variable.

2023-02-10 20:04 UTC, philvarner approved these changes

2023-02-10 20:06 UTC, merged