Add Launch Your Own Viewer Button
Element84/filmdrop-ui pull request #42
Opened 2023-02-27 19:16 UTC by lucyhutcheson

**Related Issue(s):**

- n/a

**Proposed Changes:**

1. Add Launch Your Own Viewer Button

**PR Checklist:**

- [X] I have added my changes to the [CHANGELOG](https://github.com/Element84/filmdrop-ui/blob/main/CHANGELOG.md) **or** a CHANGELOG entry is not required.

2023-02-27 19:52 UTC, philvarner commented on src/components/LaunchModal/LaunchModal.js
> +    'https://s3.amazonaws.com/templates/GeospatialViewer.template'
this should be a configurable parameter with no default, and should drive whether or not the button is displayed (rather than REACT_APP_SHOW_LAUNCH_BTN)

2023-02-27 19:53 UTC, philvarner commented on src/components/LaunchModal/LaunchModal.js
> +      'https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create',
```suggestion
      'https://console.aws.amazon.com/cloudformation/home#/stacks/create',
```

2023-02-27 19:56 UTC, philvarner commented on src/components/LaunchModal/LaunchModal.js
> +          </p>
EoAWS headers/text needs to be configurable rather than hard-coded here.

2023-02-27 19:58 UTC, philvarner commented on src/components/LaunchModal/LaunchModal.js
> +            <li>Launch your own viewer</li>
Viewer reference needs to be configurable. This can probably reuse the same value as line 53.

2023-02-27 19:59 UTC, philvarner commented on src/components/LaunchModal/LaunchModal.js
> +              Copy and paste this template URL into the “Amazon S3 URL” field:
These look like smartquotes instead of `"` and should be replaced with normal double-quotes.

2023-02-27 20:01 UTC, philvarner requested changes
changes requested in comments.

2023-02-27 20:09 UTC, lucyhutcheson commented on src/components/LaunchModal/LaunchModal.js
> +      'https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create',
This has been updated

2023-02-27 22:46 UTC, lucyhutcheson commented on src/components/LaunchModal/LaunchModal.js
> +          </p>
This has been added as REACT_APP_APP_NAME

2023-02-27 22:47 UTC, lucyhutcheson commented on src/components/LaunchModal/LaunchModal.js
> +            <li>Launch your own viewer</li>
This has been added as REACT_APP_APP_NAME

2023-02-27 22:49 UTC, lucyhutcheson commented on src/components/LaunchModal/LaunchModal.js
> +              Copy and paste this template URL into the “Amazon S3 URL” field:
This has been fixed.

2023-02-27 22:51 UTC, lucyhutcheson commented on src/components/Layout/Content/BottomContent/BottomContent.js
> +            Launch Your Own Viewer
This has been resolved.

2023-02-27 22:52 UTC, lucyhutcheson commented on src/components/LaunchModal/LaunchModal.js
> +              Copy and paste this template URL into the “Amazon S3 URL” field:
This has been resolved.

2023-02-28 13:56 UTC, philvarner commented on src/components/Layout/Content/BottomContent/BottomContent.js
> +  const CF_TEMPLATE_URL = process.env.REACT_APP_AWS_CF_TEMPLATE
I'd like to have "URL" in the config variable name, `REACT_APP_AWS_CF_TEMPLATE_URL`

2023-02-28 14:15 UTC, philvarner commented on src/components/LaunchModal/LaunchModal.js
> +  const appName = process.env.REACT_APP_APP_NAME
these need to be added to the README

2023-02-28 14:16 UTC, philvarner commented on src/components/Layout/Content/BottomContent/BottomContent.js
> +    process.env.REACT_APP_LAUNCH_BTN_TEXT || 'Launch Your Own FilmDrop UI'
needs to be added to the README

2023-02-28 14:18 UTC, philvarner commented on .env.example
> +REACT_APP_SHOW_LAUNCH_BTN=false
remove. Don't include the new config vars in the example file, since they're not something many admins will want to configure.

2023-02-28 14:18 UTC, philvarner commented on CHANGELOG.md
> +- Env variable REACT_APP_SHOW_LAUNCH_BTN
changelog needs to be updated with the new config vars

2023-02-28 14:18 UTC, philvarner commented on README.md
> +| REACT_APP_SHOW_LAUNCH_BTN    | Flag for displaying the Launch button at the bottom left of the UI. Setting to `true` will display the button, any other value will not display the button. Default is
remove, and add the others

2023-02-28 14:19 UTC, philvarner commented on src/components/LaunchModal/LaunchImageModal.js
> +            alt="Screenshot of Cloud Formation Template field"
```suggestion
            alt="Screenshot of CloudFormation Template field"
```

2023-02-28 14:21 UTC, philvarner commented on src/components/LaunchModal/LaunchModal.js
> +// you need to import each action you need to use
maybe remove these comments? they seem they were from a code example rather than added to actually describe the code beyond what's apparent.

2023-02-28 14:21 UTC, philvarner commented on src/components/LaunchModal/LaunchModal.js
> +  // if you are setting redux state, call dispatch
same for this one.

2023-02-28 14:22 UTC, philvarner commented on src/components/LaunchModal/LaunchModal.js
> +              Copy and paste this template URL into the &ldquo;Amazon S3
maybe use regular double quotes here rather than smart quotes?

2023-02-28 14:24 UTC, philvarner requested changes
changes requested in comments

2023-02-28 16:07 UTC, lucyhutcheson commented on src/components/Layout/Content/BottomContent/BottomContent.js
> +  const CF_TEMPLATE_URL = process.env.REACT_APP_AWS_CF_TEMPLATE
This has been changed.

2023-02-28 16:20 UTC, lucyhutcheson commented on src/components/LaunchModal/LaunchModal.js
> +  const appName = process.env.REACT_APP_APP_NAME
These have been added.

2023-02-28 16:21 UTC, lucyhutcheson commented on src/components/Layout/Content/BottomContent/BottomContent.js
> +    process.env.REACT_APP_LAUNCH_BTN_TEXT || 'Launch Your Own FilmDrop UI'
These have been added.

2023-02-28 16:59 UTC, lucyhutcheson commented on .env.example
> +REACT_APP_SHOW_LAUNCH_BTN=false
This has been removed.

2023-02-28 17:00 UTC, lucyhutcheson commented on CHANGELOG.md
> +- Env variable REACT_APP_SHOW_LAUNCH_BTN
They have been added.

2023-02-28 17:02 UTC, lucyhutcheson commented on README.md
> +| REACT_APP_SHOW_LAUNCH_BTN    | Flag for displaying the Launch button at the bottom left of the UI. Setting to `true` will display the button, any other value will not display the button. Default is
This has been removed.

2023-02-28 17:03 UTC, lucyhutcheson commented on src/components/LaunchModal/LaunchImageModal.js
> +            alt="Screenshot of Cloud Formation Template field"
This has been resolved.

2023-02-28 17:04 UTC, lucyhutcheson commented on src/components/LaunchModal/LaunchModal.js
> +// you need to import each action you need to use
These have been removed.

2023-02-28 17:05 UTC, lucyhutcheson commented on src/components/LaunchModal/LaunchModal.js
> +  // if you are setting redux state, call dispatch
This has been removed.

2023-02-28 17:14 UTC, lucyhutcheson commented on src/components/LaunchModal/LaunchModal.js
> +              Copy and paste this template URL into the &ldquo;Amazon S3
This has been resolved.

2023-02-28 17:14 UTC, lucyhutcheson commented on src/components/LaunchModal/LaunchImageModal.js
> +          <h3>On the &ldquo;Create stack&rdquo; page</h3>
This has been resolved.

2023-02-28 17:52 UTC, philvarner commented on src/components/LaunchModal/LaunchModal.js
> +  const appName = process.env.REACT_APP_APP_NAME
```suggestion
  const appName = process.env.REACT_APP_APP_NAME || "FilmDrop UI"
```

2023-02-28 17:53 UTC, philvarner commented on src/components/LaunchModal/LaunchModal.js
> +  const appName = process.env.REACT_APP_APP_NAME
This should have a default so the places that use it don't have an odd missing word if it's not defined.

2023-02-28 17:56 UTC, philvarner commented on src/components/Layout/Content/BottomContent/BottomContent.js
> +    process.env.REACT_APP_LAUNCH_BTN_TEXT || 'Launch Your Own FilmDrop UI'
Instead of a separate REACT_APP_LAUNCH_BTN_TEXT config, I think just using `Launch Your Own {appName}` would be fine here, especially since we don't have configurations for the few other places where we use `Launch Your Own`

2023-02-28 17:56 UTC, philvarner requested changes
inline comments

2023-02-28 18:35 UTC, lucyhutcheson commented on src/components/LaunchModal/LaunchModal.js
> +  const appName = process.env.REACT_APP_APP_NAME
This has been changed.

2023-02-28 19:00 UTC, lucyhutcheson commented on src/components/Layout/Content/BottomContent/BottomContent.js
> +    process.env.REACT_APP_LAUNCH_BTN_TEXT || 'Launch Your Own FilmDrop UI'
This has been resolved.

2023-02-28 19:51 UTC, philvarner commented on src/components/LaunchModal/LaunchModal.js
> +  const transitionalWord = startsWithVowel(APP_NAME) ? 'an' : 'a'
I don't think we need an indefinite article before the app name -- I think it sounds fine without it.

2023-02-28 19:59 UTC, lucyhutcheson commented on src/components/LaunchModal/LaunchModal.js
> +  const transitionalWord = startsWithVowel(APP_NAME) ? 'an' : 'a'
This has been removed.

2023-02-28 21:53 UTC, philvarner commented on src/components/LaunchModal/LaunchModal.js
> +            Now you can view your own datasets by deploying an
```suggestion
            Now you can view your own datasets by deploying
```

2023-02-28 21:54 UTC, philvarner commented on src/components/LaunchModal/LaunchModal.js
> +            Now you can view your own datasets by deploying an
we don't need the indefinite article at all, and especially if it's going to be grammatically incorrect in many cases.

2023-02-28 23:49 UTC, lucyhutcheson commented on src/components/LaunchModal/LaunchModal.js
> +            Now you can view your own datasets by deploying an
This has been resolved.

2023-03-01 13:15 UTC, philvarner approved these changes

2023-03-01 14:18 UTC, philvarner commented
Merging this so I can deploy it

2023-03-01 14:19 UTC, merged