Lh/filter cloud collection
Element84/filmdrop-ui pull request #45
Opened 2023-03-01 18:59 UTC by lucyhutcheson

**Related Issue(s):**

- #44 

**Proposed Changes:**

1.  Enable filtering of cloud slider based on collection
2. Remove time from date range

**PR Checklist:**

- [X] I have added my changes to the [CHANGELOG](https://github.com/Element84/filmdrop-ui/blob/main/CHANGELOG.md) **or** a CHANGELOG entry is not required.

2023-03-01 19:57 UTC, philvarner commented on src/components/CloudSlider/CloudSlider.js
> +        .catch((err) => {
the default if /queryables returns a 404 should be to display the slider -- does this do that?

This should also be looking up the href for the queryables endpoint from the collection metadata rather than just getting that /queryables endpoint directly, which is how you know that queryables is implemented at all. We have a number of issues like this that need addressing if this is going to work on any STAC API and not just EarthSearch, so I think doing it this way is fine for now, but we'll need to revisit it in the future.

2023-03-01 19:59 UTC, philvarner commented on src/components/CloudSlider/CloudSlider.js
> +        .catch((err) => {
actually, maybe it shouldn't display the slider if it can't get the /queryables endpoint. The issue is that stac-server is the only server that implements queryables, but we'd like this to work against other APIs with datasets that don't have cloud_cover, and not enabling it is the only way to do that.

2023-03-01 20:02 UTC, philvarner commented on src/components/Search/Search.js
>        '-' +
this would be clearer as an interpolated backtick string

2023-03-01 20:03 UTC, philvarner commented on src/components/Search/Search.js
> +    let cloudCover = '%20'
```suggestion
    let cloudCover = ''
```

2023-03-01 20:04 UTC, philvarner requested changes
comments inline

2023-03-01 20:19 UTC, lucyhutcheson commented on src/components/Search/Search.js
>        '-' +
It looks harder to read in this line:     
const dateString = `${dateTime.getUTCFullYear()}-${('0' + (dateTime.getUTCMonth() + 1)).slice(-2)}-${('0' + dateTime.getUTCDate()).slice(-2)}T00:00:00Z`

2023-03-01 20:21 UTC, lucyhutcheson commented on src/components/Search/Search.js
> +    let cloudCover = '%20'
This has been resolved.

2023-03-01 21:22 UTC, philvarner commented on src/components/Search/Search.js
>        '-' +
oh yeah -- the pr view cut off the first part of that expression. this is fine.

2023-03-01 21:34 UTC, philvarner commented on src/components/CloudSlider/CloudSlider.js
> +          }
I'm not exactly sure what the precedence of !! is, so wrapped the expression in ( ) just to be safe and clear

2023-03-01 21:38 UTC, lucyhutcheson commented on src/components/CloudSlider/CloudSlider.js
> +          }
This has been updated.

2023-03-02 13:36 UTC, philvarner approved these changes

2023-03-02 14:33 UTC, merged