Add rescale, colormap, expression tiler parameters
Element84/filmdrop-ui pull request #62
Opened 2023-03-15 21:01 UTC by lucyhutcheson

**Related Issue(s):**

- n/a

**Proposed Changes:**

1.  Create new REACT_APP_MOSAIC_TILER_PARAMS env variable
2.  Add support for `rescale`, `colormap_name`, `expression` tiler parameters

**PR Checklist:**

- [X] I have added my changes to the [CHANGELOG](https://github.com/Element84/filmdrop-ui/blob/main/CHANGELOG.md) **or** a CHANGELOG entry is not required.

2023-03-16 02:56 UTC, philvarner commented on .env.example
> +REACT_APP_MOSAIC_TILER_PARAMS={ "sentinel-2-l2a": { "assets": [ "visual" ] }, "landsat-c2-l2": { "assets": [ "red" ], "color_formula": "Gamma+RGB+1.7+Saturation+1.7+Sigmoidal+RGB+15+0.35" }, "naip":
```suggestion
REACT_APP_MOSAIC_TILER_PARAMS={ "sentinel-2-l2a": { "assets": [ "visual" ] }, "landsat-c2-l2": { "assets": [ "red" ], "color_formula": "Gamma+RGB+1.7+Saturation+1.7+Sigmoidal+R+15+0.35" }, "naip": { "assets": [ "image" ], "bidx": "1,2,3" }, "cop-dem-glo-30": { "assets": [ "data" ], "colormap_name": "terrain", "rescale":["-1000,4000"]}, "cop-dem-glo-90": { "assets": [ "data" ], "colormap_name": "terrain", "rescale":["-1000,4000"]}, "sentinel-1-grd": { "assets": [ "vv" ], "rescale": ["0,250"], "colormap_name": "plasma"} }
```

2023-03-16 02:59 UTC, philvarner commented on README.md
> +| REACT_APP_MOSAIC_TILER_PARAMS | Per-collection configuration of TiTiler mosaic `assets`, `color_formula`, `bidx`, `rescale`, and `colormap_name` parameters. Example in [.env.example](.env.example)
mention `expression` in this and the other one

2023-03-16 12:22 UTC, philvarner commented on CHANGELOG.md
> +- Move mosaic-specific tiler parameters (`mosaic_asset` and `mosaic_color_formula`) into new env variable REACT_APP_MOSAIC_TILER_PARAMS
```suggestion
- Move mosaic-specific tiler parameters (`mosaic_asset` and `mosaic_color_formula`) into new env variable REACT_APP_MOSAIC_TILER_PARAMS, and rename them to `assets` and `color_formula` to align with scene view tiler parameters.
```

2023-03-16 12:24 UTC, philvarner commented on src/components/Search/Search.js
> +        if (tilerURL.length > 0) {
```suggestion
        if (tilerURL) {
```

an empty string is falsy, and this is easier to read

2023-03-16 12:35 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +// retrieve tiler params from env variables for scene and mosaic
these could be one method that takes as a parameter the name of the env var, and then accesses it with index syntax `process.env[configVariable]` instead of using object attribute syntax. Then you could have getSceneTilerParams and getMosaicTilerParams that both call that shared method with the appropriate param name.

2023-03-16 12:36 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +const getTilerParams = () => {
I think we need to be explicit in these methods with names including "scene" or "mosaic", instead of just having the methods without mosaic in the name be the scene tiler

2023-03-16 12:39 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +
these 3 and color_formula should be refactored out into a method that's shared by both constructTilerParams and constructMosaicTilerParams. Doing that for assets and bidx would be ideal, but much trickier to the point that it's probably less clear what's going on.

2023-03-16 12:40 UTC, philvarner requested changes
looks good, and I tested it works. Minor refactoring changes requested in comments.

2023-03-16 14:55 UTC, lucyhutcheson commented on .env.example
> +REACT_APP_MOSAIC_TILER_PARAMS={ "sentinel-2-l2a": { "assets": [ "visual" ] }, "landsat-c2-l2": { "assets": [ "red" ], "color_formula": "Gamma+RGB+1.7+Saturation+1.7+Sigmoidal+RGB+15+0.35" }, "naip":
This has been resolved.

2023-03-16 14:56 UTC, lucyhutcheson commented on CHANGELOG.md
> +- Move mosaic-specific tiler parameters (`mosaic_asset` and `mosaic_color_formula`) into new env variable REACT_APP_MOSAIC_TILER_PARAMS
This has been resolved.

2023-03-16 15:12 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +// retrieve tiler params from env variables for scene and mosaic
Great suggestion. This has been added.

2023-03-16 15:28 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +const getTilerParams = () => {
This has been resolved.

2023-03-16 16:29 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +
These have been moved into a method.

2023-03-16 16:33 UTC, lucyhutcheson commented on README.md
> +| REACT_APP_MOSAIC_TILER_PARAMS | Per-collection configuration of TiTiler mosaic `assets`, `color_formula`, `bidx`, `rescale`, and `colormap_name` parameters. Example in [.env.example](.env.example)
This has been added to the scene tiler params.

2023-03-20 14:36 UTC, philvarner commented on README.md
> +| REACT_APP_MOSAIC_TILER_PARAMS | Per-collection configuration of TiTiler mosaic `assets`, `color_formula`, `bidx`, `rescale`, and `colormap_name` parameters. Example in [.env.example](.env.example)
```suggestion
| REACT_APP_MOSAIC_TILER_PARAMS | Per-collection configuration of TiTiler mosaic `assets`, `color_formula`, `bidx`, `rescale`, `expression`, and `colormap_name` parameters. Example in [.env.example](.env.example)                                                              | Optional |
```

2023-03-20 14:38 UTC, philvarner commented on src/components/Search/Search.js
> +          console.log('REACT_APP_TILER_URL is not set in env variables.')
```suggestion
          console.log('REACT_APP_SCENE_TILER_URL is not set in env variables.')
```

2023-03-20 14:43 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +    return asset.toString()
```suggestion
    return asset.pop()
```

2023-03-20 14:46 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +  if (colormap) params.push(colormap)
```suggestion
  const colormapName = parameters.colormapName(tilerParams, collection)
  if (colormapName) params.push(colormapName)
```

2023-03-20 14:47 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +  colorFormula: function (tilerParams, collection) {
I prefer fat-arrow functions in cases like this

```suggestion
  colorFormula: (tilerParams, collection) => {
```

2023-03-20 14:47 UTC, philvarner commented on src/components/Search/envVarSetup.js
> +      const assetBidx = asset && value ? `${asset}|${value}` : null
nice

2023-03-20 15:41 UTC, lucyhutcheson commented on README.md
> +| REACT_APP_MOSAIC_TILER_PARAMS | Per-collection configuration of TiTiler mosaic `assets`, `color_formula`, `bidx`, `rescale`, and `colormap_name` parameters. Example in [.env.example](.env.example)
This has been added.

2023-03-20 15:47 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +  if (!assets || assets.length < 1) {
The variable was set to default to an array. I changed it to a string as the default and removed the code. This has been completed.

2023-03-20 15:49 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +    return asset.toString()
This has been completed.

2023-03-20 15:50 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +  if (colormap) params.push(colormap)
This has been resolved.

2023-03-20 15:56 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +  colorFormula: function (tilerParams, collection) {
This has been resolved.

2023-03-20 15:58 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +      const assetBidx = asset && value ? `${asset}|${value}` : null
Thanks!

2023-03-20 15:58 UTC, lucyhutcheson commented on src/components/Search/envVarSetup.js
> +  colormap: function (tilerParams, collection) {
This has been updated.

2023-03-20 16:01 UTC, lucyhutcheson commented on src/components/Search/Search.js
> +          console.log('REACT_APP_TILER_URL is not set in env variables.')
This has been updated.

2023-03-20 17:37 UTC, philvarner commented on CHANGELOG.md
> +- Env variable REACT_APP_MOSAIC_TILER_PARAMS
goood point

2023-03-20 17:38 UTC, merged