Lh/aggregate results
Element84/filmdrop-ui pull request #93
Opened 2023-04-06 22:52 UTC by lucyhutcheson

**Related Issue(s):**

- N/A

**Proposed Changes:**

1.  Add aggregated results view at medium zoom levels

**PR Checklist:**

- [X] I have added my changes to the [CHANGELOG](https://github.com/Element84/filmdrop-ui/blob/main/CHANGELOG.md) **or** a CHANGELOG entry is not required.

2023-04-10 13:32 UTC, philvarner commented on src/components/Layout/Content/BottomContent/BottomContent.js
> +      {_searchResults !== null && !!_searchResults.context?.matched ? (
```suggestion
      {!!_searchResults?.context?.matched ? (
```

2023-04-10 13:33 UTC, philvarner commented on src/components/Layout/Content/BottomContent/BottomContent.js
> +      {_searchResults !== null && !!_searchResults.context?.total_scenes ? (
```suggestion
      {!!_searchResults?.context?.total_scenes ? (
```

2023-04-10 13:52 UTC, philvarner commented on src/components/LeafMap/LeafMap.js
> +            start: 'Click and drag to draw bounding box.'
why is this here if we're not drawing a bbox?

2023-04-10 13:52 UTC, philvarner commented on src/components/LeafMap/LeafMap.js
> +    if (map && Object.keys(map).length > 0) {
```suggestion
    if (map && Object.keys(map).length) {
```

2023-04-10 13:55 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +  if (selectedCollection.startsWith('sentinel')) {
```suggestion
  if (selectedCollection.startsWith('sentinel-2')) {
```
This gridding is only for sentinel-2-l1c and sentinel-2-l2a

2023-04-10 13:55 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +
naip?

2023-04-10 14:01 UTC, philvarner commented
I'm not sure how "medium" zoom level is defined, but I'm seeing the scene view at low zoom levels with REACT_APP_MIN_ZOOM_LEVEL=7

2023-04-10 14:03 UTC, philvarner commented
I'm seeing the scene view at low zoom levels, then aggregate view at medium, then back to scene at high zoom.

2023-04-10 14:05 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +  const responseData = await fetch(`/data/${selectedCollection}.json`)
this data file is very large and needs to be cached so it's only fetched once ever. Ideally, this should be done asynchronously as the web app load, so it's ready when the user makes the first medium-zoom level request.

2023-04-10 17:35 UTC, philvarner commented on src/components/LeafMap/LeafMap.js
> +    iconUrl: 'https://unpkg.com/leaflet@1.6/dist/images/marker-icon.png',
should we rely on this 3rd party URL, or include this image in the app deployment?

2023-04-10 17:37 UTC, philvarner requested changes
inline

2023-04-10 18:44 UTC, lucyhutcheson commented on src/components/Layout/Content/BottomContent/BottomContent.js
> +      {_searchResults !== null && !!_searchResults.context?.matched ? (
This has been resolved.

2023-04-10 19:03 UTC, lucyhutcheson commented on src/components/Layout/Content/BottomContent/BottomContent.js
> +      {_searchResults !== null && !!_searchResults.context?.matched ? (
This has been updated.

2023-04-10 19:03 UTC, lucyhutcheson commented on src/components/Layout/Content/BottomContent/BottomContent.js
> +      {_searchResults !== null && !!_searchResults.context?.total_scenes ? (
This has been updated.

2023-04-10 19:04 UTC, lucyhutcheson commented on src/components/LeafMap/LeafMap.js
> +            start: 'Click and drag to draw bounding box.'
This has been removed.

2023-04-10 19:05 UTC, lucyhutcheson commented on src/components/LeafMap/LeafMap.js
> +    if (map && Object.keys(map).length > 0) {
This has been resolved.

2023-04-10 19:06 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +  if (selectedCollection.startsWith('sentinel')) {
This has been updated.

2023-04-10 19:17 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +
NAIP has been added.

2023-04-10 19:33 UTC, lucyhutcheson commented on src/components/LeafMap/LeafMap.js
> +    iconUrl: 'https://unpkg.com/leaflet@1.6/dist/images/marker-icon.png',
This has been added.

2023-04-11 16:15 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +  const responseData = await fetch(`/data/${selectedCollection}.json`)
This has been updated.

2023-04-12 12:55 UTC, philvarner commented on src/components/Layout/Content/BottomContent/BottomContent.js
> +      {_searchResults?.context?.matched ? (
```suggestion
      {_searchResults?.numberMatched ? (
```

2023-04-12 13:05 UTC, philvarner commented on src/components/Search/Search.js
> +    const dataFiles = ['cdem', 'landsat', 'naip', 'sentinel']
I'd like these files to be named according to the grid code prefix in them rather than the dataset that uses them, so cdem, wrs2, doqq, and mgrs.

2023-04-12 13:12 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +  let preKey = ''
Ideally, there would be a way to load the grid definitions, either eagerly or when first used, so the collection names don't have to be hard-coded here. If the grid definitions are processed when first used, the grid prefix (e.g., MGRS) could be used to determine which file to load in rather than by collection name. However, I don't think it's using too much memory just to load all of them when the app first starts, and then it's much faster when the grid is actually displayed.

2023-04-12 13:13 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +  if (selectedCollection === 'landsat') {
This doesn't need to check if the collection is landsat -- it can just look for grid_code_frequency and if that doesn't exist, then look for grid_code_landsat_frequency

2023-04-12 13:16 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +  const searchURL = `${process.env.REACT_APP_STAC_API_URL}/aggregate?${searchParamsStr}`
I'm about to make a change here where this endpoint will only return the aggregations that are specifically requested, so another parameter `aggregations=grid_code_frequency,grid_code_landsat_frequency,total_count` should also be passed

2023-04-12 13:19 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +    }
```suggestion
    const geometry = mappedDataFile.get(apiValue)
    if (geometry) {
      mappedKeys.push({
      geometry,
      type: 'Feature',
      properties: {
        'grid:code': value.key,
        frequency: value.frequency
      }
    })
    }
```

2023-04-12 13:20 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +  mappedResults = { features: mappedKeys, context }
```suggestion
  return { features: mappedKeys, context }
```
remove the mappedResults variable entirely

2023-04-12 13:23 UTC, philvarner commented on src/components/Search/SearchAPI.js
> +    const apiValue = value.key
```suggestion
  const mappedKeys = apikeys.buckets.map((value) => {
    const apiValue = value.key
    // the code below, but returning the Feature rather than pushing it onto mapped Keys
    }.filter((x) => x) // removes any nulls from when the geometry mapping doesn't exist
```
(this suggestion can't be committed, I was just using it to demonstrate)

2023-04-12 13:25 UTC, philvarner requested changes
changes requested in comments.

2023-04-12 13:38 UTC, philvarner commented
I'd like to see a configuration for how many grid squares get displayed (currently I think the API is only returning 1000, but I can I think I should increase this).

2023-04-12 15:28 UTC, lucyhutcheson commented on src/components/Layout/Content/BottomContent/BottomContent.js
> +      {_searchResults?.context?.matched ? (
This has been updated.

2023-04-12 15:51 UTC, lucyhutcheson commented on src/components/Search/Search.js
> +    const dataFiles = ['cdem', 'landsat', 'naip', 'sentinel']
This has been completed.

2023-04-12 17:01 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +  if (selectedCollection === 'landsat') {
This has been updated.

2023-04-13 15:49 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +    }
This has been resolved.

2023-04-13 21:23 UTC, lucyhutcheson commented on src/components/Search/Search.js
> +    let typeOfSearch = { type: 'scene' }
Will be added in next PR

2023-04-13 21:25 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +  if (selectedCollection === 'landsat') {
This has been resolved.

2023-04-13 21:25 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +  const searchURL = `${process.env.REACT_APP_STAC_API_URL}/aggregate?${searchParamsStr}`
This has been added.

2023-04-13 21:34 UTC, lucyhutcheson commented on src/components/Search/SearchAPI.js
> +    const apiValue = value.key
This has been resolved.

2023-04-14 14:54 UTC, philvarner commented on src/utils/setupBounds.js
> +  if (coordinates[0].length === 1) {
maybe add a comment indicating that this is how to tell a Polygon from a MultiPolygon?

Also, add that we're assuming the Polygon has a single LineString within it defining the footprint, without holes.

2023-04-14 16:06 UTC, lucyhutcheson commented on src/utils/setupBounds.js
> +  if (coordinates[0].length === 1) {
Removed this function as it was unused.

2023-04-14 18:46 UTC, philvarner commented on src/components/Search/SearchParameters.js
> +      query['landsat:wrs_row'] = { eq: gridCodeSplit.slice(-3) }
```suggestion
      # extract the path and row from gridcode value, e.g., WRS2-123123
      query['landsat:wrs_path'] = { eq: gridCode.substring(5, 8) }
      query['landsat:wrs_row'] = { eq: gridCode.substring(8, 11) }
```

2023-04-14 18:46 UTC, philvarner approved these changes

2023-04-14 19:34 UTC, merged

2023-04-14 19:50 UTC, lucyhutcheson commented on src/components/Search/SearchParameters.js
> +      query['landsat:wrs_row'] = { eq: gridCodeSplit.slice(-3) }
This has been added to the next PR.